# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RelayServerRPC.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14RelayServerRPC.proto\x12\x0bRelayServer\"7\n\treqSpeech\x12\x16\n\x0c\x61udioContent\x18\x01 \x01(\x0cH\x00\x42\x12\n\x10streamingRequest\")\n\x07resText\x12\x10\n\x08resultCd\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t2F\n\x0bRelayServer\x12\x37\n\x03STT\x12\x16.RelayServer.reqSpeech\x1a\x14.RelayServer.resText\"\x00(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RelayServerRPC_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQSPEECH._serialized_start=37
  _REQSPEECH._serialized_end=92
  _RESTEXT._serialized_start=94
  _RESTEXT._serialized_end=135
  _RELAYSERVER._serialized_start=137
  _RELAYSERVER._serialized_end=207
# @@protoc_insertion_point(module_scope)
